site_name: Notes
site_description: 'Notes de d√©veloppement'
site_author: 'Romain Quencez'
docs_dir: docs/
repo_name: 'romainquencez/notes'
repo_url: 'https://github.com/romainquencez/notes/'
nav:
  - Accueil: index.md
  - git: git.md
  - PHP: php.md
  - Symfony: symfony.md
  - Linux: linux.md
  - Keycloak: keycloak.md
theme:
  name: 'material'
  language: fr
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
